import streamlit as st
import pandas as pd
from datetime import datetime

def generate_csv_report(elec_units, elec_co2, travel_km, travel_co2, waste_kg, waste_co2, total_co2, annual_tons):
    """Generates a CSV string representation of the carbon footprint analysis."""
    df = pd.DataFrame([
        {"Category": "Electricity Consumption", "Input Value": f"{elec_units} units/month", "Factor": "0.82 kg CO2/unit", "Monthly Emission (kg CO2)": elec_co2},
        {"Category": "Transportation Travel", "Input Value": f"{travel_km} km/month", "Factor": "0.21 kg CO2/km", "Monthly Emission (kg CO2)": travel_co2},
        {"Category": "Waste Generation", "Input Value": f"{waste_kg} kg/month", "Factor": "0.45 kg CO2/kg", "Monthly Emission (kg CO2)": waste_co2},
        {"Category": "TOTAL MONTHLY FOOTPRINT", "Input Value": "-", "Factor": "-", "Monthly Emission (kg CO2)": total_co2},
        {"Category": "PROJECTED ANNUAL FOOTPRINT", "Input Value": "-", "Factor": "-", "Monthly Emission (kg CO2)": f"{annual_tons} Metric Tonnes/year"}
    ])
    return df.to_csv(index=False)

def generate_txt_report(elec_units, elec_co2, travel_km, travel_co2, waste_kg, waste_co2, total_co2, annual_tons):
    """Generates a formatted text summary report."""
    timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    report = f"""==================================================
🌍 CARBON FOOTPRINT ASSESSMENT REPORT (SDG 13)
Timestamp: {timestamp}
==================================================

1. INPUT METRICS & EMISSIONS BREAKDOWN
--------------------------------------------------
• Electricity Usage: {elec_units} units/month
  -> Emission Factor: 0.82 kg CO2 / unit
  -> Calculated Emission: {elec_co2} kg CO2

• Transportation Travel: {travel_km} km/month
  -> Emission Factor: 0.21 kg CO2 / km
  -> Calculated Emission: {travel_co2} kg CO2

• Waste Generated: {waste_kg} kg/month
  -> Emission Factor: 0.45 kg CO2 / kg
  -> Calculated Emission: {waste_co2} kg CO2

2. SUMMARY OUTCOME
--------------------------------------------------
• Total Monthly Footprint : {total_co2} kg CO2
• Projected Annual Footprint: {annual_tons} Metric Tonnes / year

3. BENCHMARK COMPARISON
--------------------------------------------------
• India National Average  : ~1.90 Tonnes CO2 / year
• Global Per Capita Target: ~2.00 Tonnes CO2 / year

==================================================
Generated by SDG 13 Climate Action Support System
==================================================
"""
    return report

def render_footprint_module():
    """Renders Module 2: Carbon Footprint Calculator with Report Export."""
    st.subheader("📊 Monthly Carbon Footprint Calculator")
    st.markdown("Quantify your monthly carbon output based on household energy, transportation, and waste generation.")
    
    col_inputs, col_results = st.columns([1, 1], gap="large")
    
    with col_inputs:
        st.markdown("### 📝 Enter Usage Metrics")
        electricity = st.number_input(
            "Electricity used (units/month):",
            min_value=0.0,
            value=34.0,
            help="1 Unit = 1 kWh. Factor: 0.82 kg CO2 per unit."
        )
        travel = st.number_input(
            "Travel distance (km/month):",
            min_value=0.0,
            value=4.0,
            help="Factor: 0.21 kg CO2 per km."
        )
        waste = st.number_input(
            "Waste generated (kg/month):",
            min_value=0.0,
            value=2.0,
            help="Factor: 0.45 kg CO2 per kg."
        )
        
        calc_btn = st.button("Calculate Footprint", type="primary", use_container_width=True)

    with col_results:
        st.markdown("### 📈 Footprint Analysis")
        
        # Calculate emissions using exact factors
        electricity_emission = round(electricity * 0.82, 2)
        travel_emission = round(travel * 0.21, 2)
        waste_emission = round(waste * 0.45, 2)
        
        total_emission = round(electricity_emission + travel_emission + waste_emission, 2)
        annual_emission = round((total_emission * 12) / 1000, 3)

        st.success(f"Estimated Monthly Carbon Footprint: **{total_emission} kg CO₂**")
        
        # Metric indicators
        m_col1, m_col2 = st.columns(2)
        with m_col1:
            st.metric(label="Monthly CO₂ Output", value=f"{total_emission} kg")
        with m_col2:
            st.metric(label="Projected Annual Output", value=f"{annual_emission} Tonnes")

        # Category Breakdown Chart
        st.markdown("#### Emission Source Breakdown")
        breakdown_df = pd.DataFrame({
            "Category": ["Electricity (0.82 kg/unit)", "Travel (0.21 kg/km)", "Waste (0.45 kg/kg)"],
            "CO2 Emission (kg)": [electricity_emission, travel_emission, waste_emission]
        })
        st.bar_chart(breakdown_df.set_index("Category"))

    st.markdown("---")
    
    # Export & Strategy Section
    col_strat, col_exp = st.columns([1, 1], gap="large")
    
    with col_strat:
        st.markdown("### 💡 Recommended Reduction Strategy")
        if electricity_emission >= travel_emission and electricity_emission >= waste_emission:
            st.info("⚡ **Top Emission Contributor: Electricity Usage**. Switch to LED lighting, unplug idle electronics, and choose star-rated energy efficient appliances.")
        elif travel_emission >= electricity_emission and travel_emission >= waste_emission:
            st.info("🚗 **Top Emission Contributor: Transportation**. Consider carpooling, using public transit, or combining trips to reduce total vehicle kilometers.")
        else:
            st.info("🗑️ **Top Emission Contributor: Waste Generation**. Focus on composting organic waste, recycling, and avoiding single-use plastics.")

    with col_exp:
        st.markdown("### 📥 Export Assessment Report")
        st.markdown("Download your calculated carbon footprint results for record-keeping or assignment documentation.")
        
        csv_data = generate_csv_report(electricity, electricity_emission, travel, travel_emission, waste, waste_emission, total_emission, annual_emission)
        txt_data = generate_txt_report(electricity, electricity_emission, travel, travel_emission, waste, waste_emission, total_emission, annual_emission)
        
        btn_col1, btn_col2 = st.columns(2)
        with btn_col1:
            st.download_button(
                label="📄 Download CSV Report",
                data=csv_data,
                file_name=f"carbon_footprint_report_{datetime.now().strftime('%Y%m%d')}.csv",
                mime="text/csv",
                use_container_width=True
            )
        with btn_col2:
            st.download_button(
                label="📝 Download Text Summary",
                data=txt_data,
                file_name=f"carbon_footprint_summary_{datetime.now().strftime('%Y%m%d')}.txt",
                mime="text/plain",
                use_container_width=True
            )
